In [1]:
import pandas as pd
import numpy as np

In [13]:
jobs_df = pd.read_csv('Jobs_Dataset.csv')
jobs_df

jobTitle                    position  \
0              Plant Maintenance Engineer  Plant Maintenance Engineer   
1               Adobe Analytics developer     AdobeAnalyticsdeveloper   
2                           AEM architect                Aemarchitect   
3                    Azure Administrator         Azure Administrator    
4                           AEM architect                Aemarchitect   
..                                    ...                         ...   
302                       Workday Analyst           wokday functional   
303                      Web UI Developer            Web UI Developer   
304  Workday HRIS Analyst Trainee Analyst             Trainee Analyst   
305                              Workday          Workaday Functional   
306                               Web UI                    Developer   

     minBudget  maxBudget  travelReq                              location  \
0     300000.0   600000.0       True                           {Hyderabad}   
1         14.0       15.0       True           {ChennaiBangaloreHyderabad}   
2         12.0       15.0       True                           {bangalore}   
3         14.0       16.0      False                         {"Pan India"}   
4         30.0       32.0       True                           {bangalore}   
..         ...        ...        ...                                   ...   
302        8.0       10.0      False                           {bangalore}   
303        0.0        6.0      False                           {Bangalore}   
304   250000.0   300000.0       True                           {Bengaluru}   
305        6.0       15.0      False  {"Bangalore, Chennai, Mumbai, Pune"}   
306        0.0        8.0       True                           {Bangalore}   

                                           description  \
0    Read and understand the data from P&ID, PEFS, ...   
1    An understanding of the marketing technologies...   
2    To analyze, understand the client’s business u...   
3    1.\tArchitecture and Design for large scale Az...   
4    Should have experience in java, OSGI, Componen...   
..                                                 ...   
302  Workday Certification with 8+ Years of impleme...   
303  Web UI Developer:\r\nHTML 5, CSS, Java Scripts...   
304  We support our clients around the clock. So, p...   
305  Workday Certification with 8+ Years of impleme...   
306  Web UI Developer:\r\nHTML 5, CSS, Java Scripts...   

                                            attachment  orgId    jobType  ...  \
0                                                  NaN      1  Permanent  ...   
1                                                  NaN      1  Permanent  ...   
2                                                  NaN      1  Permanent  ...   
3                                                  NaN      1  Permanent  ...   
4    https://storage.googleapis.com/hrm-musquare/jo...      1  Permanent  ...   
..                                                 ...    ...        ...  ...   
302  https://storage.googleapis.com/hrm-musquare/jo...      1  Permanent  ...   
303  https://storage.googleapis.com/hrm-musquare/jo...      1  Permanent  ...   
304                                                NaN      1  Permanent  ...   
305  https://storage.googleapis.com/hrm-musquare/jo...      1  Permanent  ...   
306  https://storage.googleapis.com/hrm-musquare/jo...      1  Permanent  ...   

    priority priceType          workType  comment  subvendorId Questionnaires  \
0       High       INR  Work from Office      NaN          NaN            NaN   
1       High       NaN               NaN      NaN          NaN            NaN   
2        Low       NaN               NaN      NaN          NaN            NaN   
3       High       INR  Work from Office      NaN          NaN            NaN   
4        NaN       NaN               NaN      NaN          NaN            NaN   
..       ...       ...               ...      ...          ... 

In [15]:
education_df = pd.read_csv("education.csv")
education_df

Id      primarySchool  primaryPercentage  primaryPassoutYear  \
0     966                NaN                  0                   0   
1     967  Marks High school                 86                1999   
2     968                NaN                  0                   0   
3     969                NaN                  0                   0   
4     976                NaN                  0                   0   
..    ...                ...                ...                 ...   
183  1200                NaN                  0                   0   
184  1201                NaN                  0                   0   
185  1202                NaN                  0                   0   
186  1203                NaN                  0                   0   
187  1204                NaN                  0                   0   

       secondarySchool  secondaryPercentage  secondaryPassoutYear graduation  \
0                  NaN                  0.0                     0        NaN   
1    Marks High school                 80.0                  2001        NaN   
2                  NaN                  0.0                     0        NaN   
3                  NaN                  0.0                     0        NaN   
4                  NaN                  0.0                     0        NaN   
..                 ...                  ...                   ...        ...   
183                NaN                  0.0                     0        NaN   
184                NaN                  0.0                     0        NaN   
185                NaN                  0.0                     0        NaN   
186                NaN                  0.0                     0        NaN   
187                NaN                  0.0                     0        NaN   

     graduationPercentage  graduationPassoutYear  orgId applicantId  \
0                     0.0                      0    NaN    AIJP1291   
1                     0.0                      0    NaN    AIJV7014   
2                     0.0                      0    NaN    AIAA7617   
3                     0.0                      0    NaN    AIRK6266   
4                     0.0                      0    NaN    AIDK9811   
..                    ...                    ...    ...         ...   
183                   0.0                      0    NaN    AISA9946   
184                   0.0                      0    NaN    AIRV8909   
185                   0.0                      0    NaN    AISN2058   
186                   0.0                      0    NaN    AIVS1326   
187                   0.0                      0    NaN    AIVV3855   

    certificates  name  degree  fieldOfStudy  percentage  certificate  \
0            NaN   NaN     NaN           NaN         NaN          NaN   
1            NaN   NaN     NaN           NaN         NaN          NaN   
2            NaN   NaN     NaN           NaN         NaN          NaN   
3            NaN   NaN     NaN           NaN         NaN          NaN   
4            NaN   NaN     NaN           NaN         NaN          NaN   
..           ...   ...     ...           ...         ...          ...   
183          NaN   NaN     NaN           NaN         NaN          NaN   
184          NaN   NaN     NaN           NaN         NaN          NaN   
185          NaN   NaN     NaN           NaN         NaN          NaN   
186          NaN   NaN     NaN           NaN         NaN          NaN   
187          NaN   NaN     NaN           NaN         NaN          NaN   

                      createdOn  
0    2024-03-08 08:48:16.349684  
1    2024-03-08 08:48:16.349684  
2    2024-03-08 08:48:16.349684  
3    2024-03-08 08:48:16.349684  
4    2024-03-08 08:48:16.349684  
..                          ...  
183  2024-03-08 08:48:16.349684  
184  2024-03-08 08:48:16.349684  
185  2024-03-08 08:48:16.349684  
186  2024-03-08 08:48:16.349684  
187  2024-03-08 08:48:16.349684  

[188 rows x 19 columns]

In [17]:
employment_df= pd.read_excel("employment.xlsx")
employment_df

employmentId uploadResume                       currentCompany  \
0               48          NaN                   ESMOB Technologies   
1               61          NaN  Lejara Global IT Solutions Pvt. Ltd   
2               62          NaN      Dhatri Info Solutions Pvt. Ltd,   
3               63          NaN                       IT Contractors   
4               64          NaN                         Novell Logic   
...            ...          ...                                  ...   
2094          2272          NaN                          LTIMindtree   
2095          2273          NaN                TestingXperts Pvt Ltd   
2096          2274          NaN            Tata Consultancy Services   
2097          2275          NaN          Zemoso Technologies Pvt Ltd   
2098          2276          NaN                                  HCL   

                   currentDesignation annualSalary  industry  \
0                  React JS Developer          3.5       1.0   
1                       RPA Developer          4.5       1.0   
2                      Java Developer       360000       1.0   
3                     Java Developer        490000       1.0   
4                     Java Developer        500000       1.0   
...                               ...          ...       ...   
2094            Azure DevOps Engineer       400000       1.0   
2095                Software Engineer       643000       1.0   
2096                  DevOps Engineer       400000       1.0   
2097                  DevOps Engineer       950000       1.0   
2098  Microsoft Azure DevOps Engineer       480000       1.0   

          functionalArea  role currentLocation  orgId  ... packageOffered  \
0     Software Developer   NaN       Hyderabad    1.0  ...            NaN   
1     Software Developer   NaN       Hyderabad    1.0  ...            NaN   
2     Software Developer   NaN       Hyderabad    1.0  ...            NaN   
3                     IT   NaN       Bangalore    1.0  ...            NaN   
4                     IT   NaN       Bangalore    1.0  ...            NaN   
...                  ...   ...             ...    ...  ...            ...   
2094         Development   NaN       Hyderabad    NaN  ...            NaN   
2095         Development   NaN         Haryana    NaN  ...            NaN   
2096         Development   NaN  Andhra Pradesh    NaN  ...            NaN   
2097         Development   NaN  Andhra Pradesh    NaN  ...            NaN   
2098         Development   NaN      Vijayawada    NaN  ...            NaN   

     lastWorkingDay  remarks  previousCompany  offerLetter experienceLetter  \
0               NaT      NaN              NaN          NaN              NaN   
1               NaT      NaN              NaN          NaN              NaN   
2               NaT      NaN              NaN          NaN              NaN   
3               NaT      NaN              NaN          NaN              NaN   
4               NaT      NaN              NaN          NaN              NaN   
...             ...      ...              ...          ...              ...   
2094            NaT      NaN              NaN          NaN              NaN   
2095            NaT      NaN              NaN          NaN              NaN   
2096            NaT      NaN              NaN          NaN              NaN   
2097            NaT      NaN              NaN          NaN              NaN   
2098     2023-11-02      NaN              NaN          NaN              NaN   

     relieveingLetter isRecent paySlips               createdOn  
0                 NaN      NaN      NaN 2024-03-08 08:49:43.961  
1                 NaN      NaN      NaN 2024-03-08 08:49:43.961  
2                 NaN      NaN      NaN 2024-03-08 08:49:43.961  
3                 NaN      NaN      NaN 2024-03-08 08:49:43.961  
4                 NaN      NaN      NaN 2024-03-08 08:49:43.961  
...               ...      ...      ...                     ...  
2094              NaN      NaN      

In [18]:
jobs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 30 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   jobTitle          307 non-null    object 
 1   position          307 non-null    object 
 2   minBudget         306 non-null    float64
 3   maxBudget         306 non-null    float64
 4   travelReq         307 non-null    bool   
 5   location          307 non-null    object 
 6   description       307 non-null    object 
 7   attachment        68 non-null     object 
 8   orgId             307 non-null    int64  
 9   jobType           307 non-null    object 
 10  skills            307 non-null    object 
 11  recruiter         307 non-null    object 
 12  client            307 non-null    object 
 13  minExp            307 non-null    float64
 14  maxExp            307 non-null    float64
 15  noticePeriod      307 non-null    object 
 16  status            307 non-null    object 
 1

### Observations from Datasets
- Key columns: jobTitle, position, skills, description, minExp, maxExp, location, jobType
### Issues:
- Missing values in minBudget, maxBudget, vacancies, etc.
- Unnecessary columns like subvendorId, Questionnaires, eligibility, responsibilities (mostly empty).

In [21]:
education_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Id                     188 non-null    int64  
 1   primarySchool          11 non-null     object 
 2   primaryPercentage      188 non-null    int64  
 3   primaryPassoutYear     188 non-null    int64  
 4   secondarySchool        8 non-null      object 
 5   secondaryPercentage    188 non-null    float64
 6   secondaryPassoutYear   188 non-null    int64  
 7   graduation             9 non-null      object 
 8   graduationPercentage   188 non-null    float64
 9   graduationPassoutYear  188 non-null    int64  
 10  orgId                  0 non-null      float64
 11  applicantId            188 non-null    object 
 12  certificates           15 non-null     object 
 13  name                   0 non-null      float64
 14  degree                 0 non-null      float64
 15  fieldO

## Observations from education dataset
- Key columns: applicantId, primaryPercentage, secondaryPercentage, graduationPercentage
### Issues:
- Many missing values (primarySchool, secondarySchool, graduation fields).
- Fields like degree, fieldOfStudy are missing entirely.

In [23]:
employment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2099 entries, 0 to 2098
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   employmentId        2099 non-null   int64         
 1   uploadResume        1600 non-null   object        
 2   currentCompany      2002 non-null   object        
 3   currentDesignation  2056 non-null   object        
 4   annualSalary        1994 non-null   object        
 5   industry            2004 non-null   float64       
 6   functionalArea      1986 non-null   object        
 7   role                0 non-null      float64       
 8   currentLocation     1999 non-null   object        
 9   orgId               1953 non-null   float64       
 10  noticePeriod        1919 non-null   object        
 11  skills              2099 non-null   object        
 12  totalWorkExp        2002 non-null   float64       
 13  minExp              0 non-null      float64     

## Employment Dataset 
- Key columns: applicantId, skills, totalWorkExp, currentDesignation, currentLocation, industry
### Issues:
- Missing values in previousCompany, expectedCtc, preferedLocation
- Irrelevant fields: offerLetter, experienceLetter, relieveingLetter, paySlips

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

In [34]:
# Clean Jobs Dataset
jobs_df = jobs_df[['jobTitle', 'skills', 'description', 'minExp', 'maxExp', 'location', 'jobType']]
jobs_df.dropna(inplace=True)  # Remove rows with missing values


In [38]:
# Clean Education Dataset
education_df = education_df[['applicantId', 'graduationPercentage']].dropna()


In [42]:
# Clean Employment Dataset
employment_df = employment_df[['applicantId', 'skills', 'totalWorkExp', 'currentDesignation', 'currentLocation']].dropna()


In [49]:
jobs_df

jobTitle  \
0              Plant Maintenance Engineer   
1               Adobe Analytics developer   
2                           AEM architect   
3                    Azure Administrator    
4                           AEM architect   
..                                    ...   
302                       Workday Analyst   
303                      Web UI Developer   
304  Workday HRIS Analyst Trainee Analyst   
305                              Workday    
306                               Web UI    

                                                skills  \
0                                {"Plant Maintenance"}   
1    {"Adobe anaytics",Agile,tableau,Marketo,"power...   
2                                {JIRA,Confluence,AEM}   
3                             {"Azure Administrator "}   
4                    {sling,jackrabbit,OSGI,felix,JCR}   
..                                                 ...   
302  {"workday tools","workday hcm functional","cor...   
303  {"HTML 5",CSS,"Java Scripts",JQuery,AngularJS,...   
304                                          {"HRIS "}   
305  {workday,"core compensation","Workday HCM","Wo...   
306                                             {html}   

                                           description  minExp  maxExp  \
0    Read and understand the data from P&ID, PEFS, ...    2.00     5.0   
1    An understanding of the marketing technologies...    3.00     4.0   
2    To analyze, understand the client’s business u...    4.00     6.0   
3    1.\tArchitecture and Design for large scale Az...    6.00     8.0   
4    Should have experience in java, OSGI, Componen...    9.96    15.0   
..                                                 ...     ...     ...   
302  Workday Certification with 8+ Years of impleme...    1.00     6.0   
303  Web UI Developer:\r\nHTML 5, CSS, Java Scripts...    2.00     3.0   
304  We support our clients around the clock. So, p...    0.00     1.0   
305  Workday Certification with 8+ Years of impleme...    1.00     1.0   
306  Web UI Developer:\r\nHTML 5, CSS, Java Scripts...    2.00     3.0   

                                 location    jobType  
0                             {Hyderabad}  Permanent  
1             {ChennaiBangaloreHyderabad}  Permanent  
2                             {bangalore}  Permanent  
3                           {"Pan India"}  Permanent  
4                             {bangalore}  Permanent  
..                                    ...        ...  
302                           {bangalore}  Permanent  
303                           {Bangalore}  Permanent  
304                           {Bengaluru}  Permanent  
305  {"Bangalore, Chennai, Mumbai, Pune"}  Permanent  
306                           {Bangalore}  Permanent  

[307 rows x 7 columns]

In [51]:
education_df

applicantId  graduationPercentage
0      AIJP1291                   0.0
1      AIJV7014                   0.0
2      AIAA7617                   0.0
3      AIRK6266                   0.0
4      AIDK9811                   0.0
..          ...                   ...
183    AISA9946                   0.0
184    AIRV8909                   0.0
185    AISN2058                   0.0
186    AIVS1326                   0.0
187    AIVV3855                   0.0

[188 rows x 2 columns]

In [53]:
employment_df

applicantId                                  skills  totalWorkExp  \
0       AISB2256                                {css,js}          2.75   
1       AIPH2278                            {RPA,python}          6.00   
2       AIST2288                 {java,spring,hibernate}          5.00   
3       AIVV2277                       {Java,Springboot}          3.00   
4       AIMV2241                       {Java,springboot}          3.00   
...          ...                                     ...           ...   
2094    AISA9946                        {"Azure Devops"}         26.00   
2095    AIRV8909  {Java,JavaScript,Hibernate,Springboot}         38.00   
2096    AISN2058                        {"Azure Devops"}         27.00   
2097    AIVS1326                      {Devops,AWS,Azure}         68.00   
2098    AIVV3855                        {"Azure Devops"}         37.00   

                   currentDesignation currentLocation  
0                  React JS Developer       Hyderabad  
1                       RPA Developer       Hyderabad  
2                      Java Developer       Hyderabad  
3                     Java Developer        Bangalore  
4                     Java Developer        Bangalore  
...                               ...             ...  
2094            Azure DevOps Engineer       Hyderabad  
2095                Software Engineer         Haryana  
2096                  DevOps Engineer  Andhra Pradesh  
2097                  DevOps Engineer  Andhra Pradesh  
2098  Microsoft Azure DevOps Engineer      Vijayawada  

[1904 rows x 5 columns]

In [55]:
# Encode Categorical Data
label_enc = LabelEncoder()
jobs_df['jobType'] = label_enc.fit_transform(jobs_df['jobType'])
jobs_df['location'] = label_enc.fit_transform(jobs_df['location'])

In [57]:
# Apply TF-IDF to job descriptions and skills
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
jobs_df['tfidf_skills'] = list(tfidf.fit_transform(jobs_df['skills'].fillna("")).toarray())


In [59]:
# Display cleaned dataset structure
jobs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   jobTitle      307 non-null    object 
 1   skills        307 non-null    object 
 2   description   307 non-null    object 
 3   minExp        307 non-null    float64
 4   maxExp        307 non-null    float64
 5   location      307 non-null    int32  
 6   jobType       307 non-null    int32  
 7   tfidf_skills  307 non-null    object 
dtypes: float64(2), int32(2), object(4)
memory usage: 16.9+ KB


In [61]:
 education_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   applicantId           188 non-null    object 
 1   graduationPercentage  188 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.1+ KB


In [63]:
employment_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1904 entries, 0 to 2098
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   applicantId         1904 non-null   object 
 1   skills              1904 non-null   object 
 2   totalWorkExp        1904 non-null   float64
 3   currentDesignation  1904 non-null   object 
 4   currentLocation     1904 non-null   object 
dtypes: float64(1), object(4)
memory usage: 89.2+ KB


## Preprocessing Done!
- Jobs dataset: Removed unnecessary columns, encoded categorical data, and applied TF-IDF on skills.
- Education dataset: Kept applicantId and graduationPercentage only.
- Employment dataset: Kept applicantId, skills, totalWorkExp, currentDesignation, and currentLocation

In [84]:
# Display actual column names of the Jobs dataset
jobs_df.columns.tolist()

['jobTitle',
 'skills',
 'minExp',
 'maxExp',
 'location',
 'jobType_1',
 'jobType_2',
 'tfidf_skills']

In [86]:
# Keep only relevant columns
jobs_df = jobs_df[['jobTitle', 'skills', 'minExp', 'maxExp', 'location', 'jobType_1', 'jobType_2', 'tfidf_skills']]

In [88]:
# Convert minExp and maxExp to numeric values (handling errors if any non-numeric values exist)
jobs_df['minExp'] = pd.to_numeric(jobs_df['minExp'], errors='coerce').fillna(0)
jobs_df['maxExp'] = pd.to_numeric(jobs_df['maxExp'], errors='coerce').fillna(jobs_df['minExp'])

In [92]:
# Show processed dataset preview
jobs_df.head()

jobTitle  \
0  Plant Maintenance Engineer   
1   Adobe Analytics developer   
2               AEM architect   
3        Azure Administrator    
4               AEM architect   

                                              skills  minExp  maxExp  \
0                              {"Plant Maintenance"}    2.00     5.0   
1  {"Adobe anaytics",Agile,tableau,Marketo,"power...    3.00     4.0   
2                              {JIRA,Confluence,AEM}    4.00     6.0   
3                           {"Azure Administrator "}    6.00     8.0   
4                  {sling,jackrabbit,OSGI,felix,JCR}    9.96    15.0   

   location  jobType_1  jobType_2  \
0        39      False       True   
1        28      False       True   
2        49      False       True   
3        19      False       True   
4        49      False       True   

                                        tfidf_skills  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

### Load and preprocess Education dataset

In [95]:
# Keep only relevant columns
education_df = education_df[['applicantId', 'graduationPercentage']]

In [97]:
# Convert graduationPercentage to numeric (handle errors if any non-numeric values exist)
education_df['graduationPercentage'] = pd.to_numeric(education_df['graduationPercentage'], errors='coerce').fillna(0)

In [103]:
# Show processed dataset preview
education_df.head()

applicantId  graduationPercentage
0    AIJP1291                   0.0
1    AIJV7014                   0.0
2    AIAA7617                   0.0
3    AIRK6266                   0.0
4    AIDK9811                   0.0

### Load and preprocess Employment dataset

In [106]:
# Keep only relevant columns
employment_df = employment_df[['applicantId', 'skills', 'totalWorkExp', 'currentDesignation', 'currentLocation']]

In [108]:
# Convert totalWorkExp to numeric (handle errors if any non-numeric values exist)
employment_df['totalWorkExp'] = pd.to_numeric(employment_df['totalWorkExp'], errors='coerce').fillna(0)

In [110]:
# Show processed dataset preview
employment_df.head()

applicantId                   skills  totalWorkExp  currentDesignation  \
0    AISB2256                 {css,js}          2.75  React JS Developer   
1    AIPH2278             {RPA,python}          6.00       RPA Developer   
2    AIST2288  {java,spring,hibernate}          5.00      Java Developer   
3    AIVV2277        {Java,Springboot}          3.00     Java Developer    
4    AIMV2241        {Java,springboot}          3.00     Java Developer    

  currentLocation  
0       Hyderabad  
1       Hyderabad  
2       Hyderabad  
3       Bangalore  
4       Bangalore

In [112]:
# Merge Education and Employment datasets on 'applicantId'
merged_df = pd.merge(education_df, employment_df, on='applicantId', how='inner')
# Merge the result with Jobs dataset (no applicantId in jobs, so we use skills-based recommendations later)
merged_df.head()

applicantId  graduationPercentage  \
0    AIBV3257                   0.0   
1    AIAM6094                   0.0   
2    AIVB5204                   0.0   
3    AICS4965                   0.0   
4    AILJ5766                   0.0   

                                              skills  totalWorkExp  \
0  {"UIUX design"," Web design","Application desi...          28.0   
1                                          {ReactJS}           0.0   
2  {"UIUX design"," Web design","Application desi...          39.0   
3  {"UIUX design","Web design","Application desig...          32.0   
4  {"UIUX design","Web design","Application desig...          42.0   

      currentDesignation currentLocation  
0  UxUi Product Designer       Hyderabad  
1                     no       Hyderabad  
2          UIUX Designer  Andhra Pradesh  
3  ASSOCIATE UX DESIGNER  Andhra Pradesh  
4            UiUx Design       Hyderabad

In [124]:
import ast
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Function to safely convert string representations of sets/lists to space-separated text
def safe_convert_skills(x):
    try:
        return ' '.join(ast.literal_eval(x)) if isinstance(x, str) else ''
    except (ValueError, SyntaxError):
        return str(x)  # If conversion fails, return the string as is

# Apply transformation to both datasets
merged_df['skills'] = merged_df['skills'].apply(safe_convert_skills)
jobs_df['skills'] = jobs_df['skills'].apply(safe_convert_skills)

# Combine skills data for consistent vocabulary
all_skills = pd.concat([merged_df['skills'], jobs_df['skills']])

# Fit TF-IDF on the combined skills data
tfidf = TfidfVectorizer(stop_words='english')
tfidf.fit(all_skills)

# Transform both datasets with the same vectorizer
tfidf_matrix_applicants = tfidf.transform(merged_df['skills'])
tfidf_matrix_jobs = tfidf.transform(jobs_df['skills'])

# Compute cosine similarity
similarity_matrix = cosine_similarity(tfidf_matrix_applicants, tfidf_matrix_jobs)

# Display similarity matrix
print(similarity_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [126]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

# Combine skills from both jobs and applicants
all_skills = jobs_df['skills'].tolist() + merged_df['skills'].tolist()


In [128]:
# Fit a single TF-IDF vectorizer on all skills
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(all_skills)

In [130]:
# Split the transformed TF-IDF matrix
tfidf_matrix_jobs = tfidf_matrix[:len(jobs_df)]
tfidf_matrix_applicants = tfidf_matrix[len(jobs_df):]


In [132]:
# Compute cosine similarity
similarity_matrix = cosine_similarity(tfidf_matrix_applicants, tfidf_matrix_jobs)


In [134]:
# Get top N recommended jobs for each applicant
top_n = 5  # Number of job recommendations per applicant
recommendations = {}

for i, applicant in enumerate(merged_df['applicantId']):
    top_job_indices = similarity_matrix[i].argsort()[-top_n:][::-1]  # Get top N job indices
    recommended_jobs = jobs_df.iloc[top_job_indices]['jobTitle'].values  # Get job titles
    recommendations[applicant] = recommended_jobs.tolist()


In [136]:
# Convert recommendations to DataFrame
recommendations_df = pd.DataFrame(list(recommendations.items()), columns=['applicantId', 'Recommended Jobs'])

# Show recommendation results
recommendations_df.head()

applicantId                                   Recommended Jobs
0    AIBV3257  [UIUX Designer, UIUX Designer , iOS Developer,...
1    AIAM6094  [ReactJS Developer, ReactJS Developer, Jr UI D...
2    AIVB5204  [UIUX Designer, UIUX Designer , iOS Developer,...
3    AICS4965  [UIUX Designer, UIUX Designer , iOS Developer,...
4    AILJ5766  [UIUX Designer, UIUX Designer , iOS Developer,...

In [138]:
# Check job dataset
jobs_df.head()


jobTitle  \
0  Plant Maintenance Engineer   
1   Adobe Analytics developer   
2               AEM architect   
3        Azure Administrator    
4               AEM architect   

                                              skills  minExp  maxExp  \
0                                  Plant Maintenance    2.00     5.0   
1  {"Adobe anaytics",Agile,tableau,Marketo,"power...    3.00     4.0   
2                              {JIRA,Confluence,AEM}    4.00     6.0   
3                               Azure Administrator     6.00     8.0   
4                  {sling,jackrabbit,OSGI,felix,JCR}    9.96    15.0   

   location  jobType_1  jobType_2  \
0        39      False       True   
1        28      False       True   
2        49      False       True   
3        19      False       True   
4        49      False       True   

                                        tfidf_skills  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [146]:
merged_df.head()

applicantId  graduationPercentage  \
0    AIBV3257                   0.0   
1    AIAM6094                   0.0   
2    AIVB5204                   0.0   
3    AICS4965                   0.0   
4    AILJ5766                   0.0   

                                              skills  totalWorkExp  \
0  Application design  Web design UIUX design Pos...          28.0   
1                                          {ReactJS}           0.0   
2  Application design  Web design UIUX design Pos...          39.0   
3  Application design UIUX design Poster design W...          32.0   
4  Application design UIUX design Poster design W...          42.0   

      currentDesignation currentLocation  
0  UxUi Product Designer       Hyderabad  
1                     no       Hyderabad  
2          UIUX Designer  Andhra Pradesh  
3  ASSOCIATE UX DESIGNER  Andhra Pradesh  
4            UiUx Design       Hyderabad

In [148]:
# Verify TF-IDF matrices
print("TF-IDF Jobs Shape:", tfidf_matrix_jobs.shape)
print("TF-IDF Applicants Shape:", tfidf_matrix_applicants.shape)

TF-IDF Jobs Shape: (307, 554)
TF-IDF Applicants Shape: (145, 554)


In [150]:
# Check similarity matrix
print("Similarity Matrix Shape:", similarity_matrix.shape)
print(similarity_matrix[:5, :5])  # Print a small portion for verification

Similarity Matrix Shape: (145, 307)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [152]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix_applicants = tfidf.fit_transform(merged_df['skills'])
tfidf_matrix_jobs = tfidf.transform(jobs_df['skills'])  # Ensure job skills are transformed too


In [176]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
# Combine skills from both jobs and applicants for consistent vectorization
all_skills = jobs_df['skills'].fillna("").tolist() + merged_df['skills'].fillna("").tolist()

In [160]:
# Fit a single TF-IDF vectorizer on all skills
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)
tfidf_matrix = vectorizer.fit_transform(all_skills)

In [162]:
# Split the transformed TF-IDF matrix
tfidf_matrix_jobs = tfidf_matrix[:len(jobs_df)]
tfidf_matrix_applicants = tfidf_matrix[len(jobs_df):]


In [164]:
# Save the TF-IDF matrices as columns in the respective dataframes
jobs_df['tfidf_skills'] = list(tfidf_matrix_jobs.toarray())
merged_df['tfidf_skills'] = list(tfidf_matrix_applicants.toarray())

In [170]:
# Compute cosine similarity
similarity_matrix = cosine_similarity(tfidf_matrix_applicants, tfidf_matrix_jobs)
print("Similarity Matrix Shape:", similarity_matrix.shape)


Similarity Matrix Shape: (145, 307)


In [172]:
# Display top 5 similarity scores
print("Top 5 Similarities:", similarity_matrix[:5, :5])

Top 5 Similarities: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [174]:
#Validate top matches for the first few applicants
for i in range(5):
    top_indices = np.argsort(-similarity_matrix[i])[:5]
    print(f"\nApplicant {i+1} Top Recommendations:")
    for idx in top_indices:
        print(f"Job Title: {jobs_df.iloc[idx]['jobTitle']}, Similarity: {similarity_matrix[i, idx]:.2f}")



Applicant 1 Top Recommendations:
Job Title: UIUX Designer, Similarity: 1.00
Job Title: UIUX Designer , Similarity: 0.77
Job Title: iOS Developer, Similarity: 0.36
Job Title: Shopify Developer, Similarity: 0.24
Job Title: Sr/Lead Java Fullstack Development, Similarity: 0.23

Applicant 2 Top Recommendations:
Job Title: Jr UI Developer, Similarity: 1.00
Job Title: ReactJS Developer, Similarity: 1.00
Job Title: ReactJS Developer, Similarity: 1.00
Job Title: Full Stack Developer - Excellerate, Similarity: 0.54
Job Title: Full Stack Developer, Similarity: 0.54

Applicant 3 Top Recommendations:
Job Title: UIUX Designer, Similarity: 1.00
Job Title: UIUX Designer , Similarity: 0.77
Job Title: iOS Developer, Similarity: 0.36
Job Title: Shopify Developer, Similarity: 0.24
Job Title: Sr/Lead Java Fullstack Development, Similarity: 0.23

Applicant 4 Top Recommendations:
Job Title: UIUX Designer, Similarity: 1.00
Job Title: UIUX Designer , Similarity: 0.77
Job Title: iOS Developer, Similarity: 0.36

In [178]:
# Convert to DataFrame and save to CSV
recommendations_df = pd.DataFrame(recommendations)
recommendations_df.to_csv('job_recommendations.csv', index=False)
print("Recommendations saved to job_recommendations.csv")

Recommendations saved to job_recommendations.csv


In [180]:
# Convert to DataFrame and save as a pickle file
recommendations_df = pd.DataFrame(recommendations)
recommendations_df.to_pickle('job_recommendations.pkl')
print("Recommendations saved to job_recommendations.pkl")


Recommendations saved to job_recommendations.pkl


In [184]:
import pandas as pd

recommendations_df = pd.read_pickle('job_recommendations.pkl')
recommendations_df.head()
recommendations_df.columns


Index(['AIBV3257', 'AIAM6094', 'AIVB5204', 'AICS4965', 'AILJ5766', 'AISP4238',
       'AIJT2556', 'AIHP2712', 'AIMS1589', 'AIVM8935',
       ...
       'AISY2729', 'AIAP2500', 'AISS4485', 'AISB6032', 'AISK8145', 'AISA9946',
       'AIRV8909', 'AISN2058', 'AIVS1326', 'AIVV3855'],
      dtype='object', length=145)

In [186]:
import pandas as pd

# Load the problematic pickle file
recommendations_df = pd.read_pickle('job_recommendations.pkl')

# Transpose the DataFrame to get the applicant IDs as a column
recommendations_df = recommendations_df.transpose().reset_index()

# Rename the columns to be consistent
recommendations_df.rename(columns={'index': 'ApplicantID'}, inplace=True)

# Save the fixed DataFrame
recommendations_df.to_pickle('job_recommendations.pkl')

print("Fixed and saved the recommendations file successfully!")


Fixed and saved the recommendations file successfully!
